Tokens:
test/test_001.in:1:1:	print	"print"	0	(1, 1) -> (1, 6)
test/test_001.in:1:6:	lparen	"("	0	(1, 6) -> (1, 7)
test/test_001.in:1:7:	number	"42"	42	(1, 7) -> (1, 9)
test/test_001.in:1:9:	rparen	")"	0	(1, 9) -> (1, 10)
test/test_001.in:2:0:	eof	""	0	(2, 0) -> (2, 0)
AST:
(module
  (print
    (number 42)
  )
)
IR:
target triple = "x86_64-pc-linux-gnu"

@0 = global [3 x i8] c"%d\00"

declare i32 @puts(i8* %str)

declare i32 @rand()

declare i32 @sprintf(i8* %buf, i8* %format, ...)

define i32 @main() {
entry:
	%0 = alloca [318 x i8]
	%1 = getelementptr [318 x i8], [318 x i8]* %0, i32 0, i32 0
	%2 = getelementptr [3 x i8], [3 x i8]* @0, i32 0, i32 0
	%3 = call i32 (i8*, i8*, ...) @sprintf(i8* %1, i8* %2, i32 42)
	%4 = call i32 @puts(i8* %1)
	ret i32 0
}

Run:
42
