Tokens:
test/test_008.in:1:1:	print	"print"	0	(1, 1) -> (1, 6)
test/test_008.in:1:6:	lparen	"("	0	(1, 6) -> (1, 7)
test/test_008.in:1:7:	lparen	"("	0	(1, 7) -> (1, 8)
test/test_008.in:1:8:	number	"34"	34	(1, 8) -> (1, 10)
test/test_008.in:1:10:	add	"+"	0	(1, 10) -> (1, 11)
test/test_008.in:1:11:	number	"35"	35	(1, 11) -> (1, 13)
test/test_008.in:1:13:	rparen	")"	0	(1, 13) -> (1, 14)
test/test_008.in:1:14:	div	"/"	0	(1, 14) -> (1, 15)
test/test_008.in:1:15:	number	"33"	33	(1, 15) -> (1, 17)
test/test_008.in:1:17:	rparen	")"	0	(1, 17) -> (1, 18)
test/test_008.in:2:0:	eof	""	0	(2, 0) -> (2, 0)
AST:
(module
  (print
    (div
      (add
        (number 34)
        (number 35)
      )
      (number 33)
    )
  )
)
IR:
target triple = "x86_64-pc-linux-gnu"

@0 = global [3 x i8] c"%d\00"

declare i32 @puts(i8* %str)

declare i32 @rand()

declare i32 @sprintf(i8* %buf, i8* %format, ...)

define i32 @main() {
entry:
	%0 = add i32 34, 35
	%1 = sdiv i32 %0, 33
	%2 = alloca [318 x i8]
	%3 = getelementptr [318 x i8], [318 x i8]* %2, i32 0, i32 0
	%4 = getelementptr [3 x i8], [3 x i8]* @0, i32 0, i32 0
	%5 = call i32 (i8*, i8*, ...) @sprintf(i8* %3, i8* %4, i32 %1)
	%6 = call i32 @puts(i8* %3)
	ret i32 0
}

Run:
2
