Tokens:
test/test_009.in:1:1:	print	"print"	0	(1, 1) -> (1, 6)
test/test_009.in:1:6:	lparen	"("	0	(1, 6) -> (1, 7)
test/test_009.in:1:7:	number	"33"	33	(1, 7) -> (1, 9)
test/test_009.in:1:9:	rparen	")"	0	(1, 9) -> (1, 10)
test/test_009.in:2:0:	print	"print"	0	(2, 0) -> (2, 5)
test/test_009.in:2:5:	lparen	"("	0	(2, 5) -> (2, 6)
test/test_009.in:2:6:	number	"34"	34	(2, 6) -> (2, 8)
test/test_009.in:2:8:	rparen	")"	0	(2, 8) -> (2, 9)
test/test_009.in:3:0:	eof	""	0	(3, 0) -> (3, 0)
AST:
(module
  (print
    (number 33)
  )
  (print
    (number 34)
  )
)
IR:
target triple = "x86_64-pc-linux-gnu"

@0 = global [3 x i8] c"%d\00"

declare i32 @puts(i8* %str)

declare i32 @rand()

declare i32 @sprintf(i8* %buf, i8* %format, ...)

define i32 @main() {
entry:
	%0 = alloca [318 x i8]
	%1 = getelementptr [318 x i8], [318 x i8]* %0, i32 0, i32 0
	%2 = getelementptr [3 x i8], [3 x i8]* @0, i32 0, i32 0
	%3 = call i32 (i8*, i8*, ...) @sprintf(i8* %1, i8* %2, i32 33)
	%4 = call i32 @puts(i8* %1)
	%5 = alloca [318 x i8]
	%6 = getelementptr [318 x i8], [318 x i8]* %5, i32 0, i32 0
	%7 = getelementptr [3 x i8], [3 x i8]* @0, i32 0, i32 0
	%8 = call i32 (i8*, i8*, ...) @sprintf(i8* %6, i8* %7, i32 34)
	%9 = call i32 @puts(i8* %6)
	ret i32 0
}

Run:
33
34
