Tokens:
test/test_004.in:1:1:	print	"print"	0	(1, 1) -> (1, 6)
test/test_004.in:1:6:	lparen	"("	0	(1, 6) -> (1, 7)
test/test_004.in:1:7:	sub	"-"	0	(1, 7) -> (1, 8)
test/test_004.in:1:8:	number	"42"	42	(1, 8) -> (1, 10)
test/test_004.in:1:10:	rparen	")"	0	(1, 10) -> (1, 11)
test/test_004.in:2:0:	eof	""	0	(2, 0) -> (2, 0)
AST:
(module
  (print
    (sub
      (number 0)
      (number 42)
    )
  )
)
IR:
target triple = "x86_64-pc-linux-gnu"

@0 = global [3 x i8] c"%d\00"

declare i32 @puts(i8* %str)

declare i32 @rand()

declare i32 @sprintf(i8* %buf, i8* %format, ...)

define i32 @main() {
entry:
	%0 = sub i32 0, 42
	%1 = alloca [318 x i8]
	%2 = getelementptr [318 x i8], [318 x i8]* %1, i32 0, i32 0
	%3 = getelementptr [3 x i8], [3 x i8]* @0, i32 0, i32 0
	%4 = call i32 (i8*, i8*, ...) @sprintf(i8* %2, i8* %3, i32 %0)
	%5 = call i32 @puts(i8* %2)
	ret i32 0
}

Run:
-42
