name: go test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25
      - uses: actions/checkout@v3
      - name: Build
        run: ./build.sh -b
      - name: Test
        run: ./build.sh -t
      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: gen/cover.out
