name: go test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: 15
          platform: x64
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: Build
        run: go build -v -o compiler ./src/...
      - name: Test
        run: go test -v ./src/...
